spring:
  application:
    name: account-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:account-service
    username: sa
    password:
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

h2:
  console:
    enabled: true
