INSERT INTO `ACCOUNT` (ID, NAME, STATUS, TYPE, BALANCE) VALUES (1, 'Medved', 'Active', 'VIP', 1002.3);
INSERT INTO `ACCOUNT` (ID, NAME, STATUS, TYPE, BALANCE) VALUES (2, 'Valera', 'Active', 'Nothing', 0.3);
INSERT INTO `ACCOUNT` (ID, NAME, STATUS, TYPE, BALANCE) VALUES (3, 'Ezh', 'Active', 'Nothing', 23.0);
INSERT INTO `ACCOUNT` (ID, NAME, STATUS, TYPE, BALANCE) VALUES (4, 'Mary', 'Active', 'VIP', 00.0);